# filepath: .pipeline/templates/test-matrix-template.yml
parameters:
  matrix: {}

jobs:
  - job: Test_Matrix
    displayName: Linux amd64 
    strategy:
      matrix: ${{ parameters.matrix }}
    pool:
      name: RUST-1ES-POOL-WUS3
      demands:
        - imageOverride -equals RUST-1ES-UBUSLIM
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '29.0.0'
      - template: install-ubuntu-dependency.yaml
        parameters:
          installAzCli: true
      - template: azure-cli-login-template.yml

      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'Build_Linux'
        displayName: 'Download Pipeline Artifacts'
      - script: |
          az acr login -n tdslibrs
          echo $(container)
          echo $(entry)
          echo $container

          scripts/generate_cert.sh
          scripts/generate_mock_tds_server_certs.sh
          
          sudo chown 10001:0 mssql.*

          if command -v docker >/dev/null 2>&1
          then
            cp $(Pipeline.Workspace)/tdslib-nextest.tar.zst $(Build.SourcesDirectory)
            
            docker network create testnet
            
            docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=$(SQL_PASSWORD)" -p 1433:1433 --hostname sql1 --network testnet -v $PWD/conf/mssql.conf:/var/opt/mssql/mssql.conf -v $PWD/mssql.pem:/etc/ssl/certs/mssql.pem -v $PWD/mssql.key:/etc/ssl/private/mssql.key -u 0:0 -d mcr.microsoft.com/mssql/server:2025-latest
            
            bash .pipeline/scripts/docker-cargo-run.sh --entrypoint bash -v "$PWD:/workspace" -e "DB_USERNAME=sa" -e "DB_HOST=sql1" -e "DB_PORT=1433" -e "SQL_PASSWORD=$(SQL_PASSWORD)" -e "ARCHIVE_NAME=tdslib-nextest.tar.zst" --network testnet $(container) /workspace/scripts/dockerentry/$(entry)
          fi
        workingDirectory: "$(Build.SourcesDirectory)"
        displayName: Run docker test
        condition: succeeded()
        env :
          SQL_PASSWORD: $(SQL_PASSWORD)
          CARGO_REGISTRIES_MSSQL_RS_PUBLIC_TOKEN: $(CARGO_REGISTRIES_MSSQL_RS_PUBLIC_TOKEN)
          CARGO_REGISTRIES_MSSQL_RS_TOKEN: $(CARGO_REGISTRIES_MSSQL_RS_TOKEN)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        displayName: "Publish test results"
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: $(Build.SourcesDirectory)/target/nextest/ci/junit.xml
          testRunTitle: $(System.PhaseName)
