# Makefile for building the C++ project with Rust dependencies

# Detect the operating system
ifeq ($(OS), Windows_NT)
    DETECTED_OS := Windows
else
    DETECTED_OS := $(shell uname -s)
endif

# Compiler and flags
ifeq ($(DETECTED_OS), Linux)
    CXX = g++
    CXXFLAGS = -lssl -lcrypto
else
    CXX = clang++
    CXXFLAGS = -std=c++11 -fexceptions
endif

# macOS-specific flags
ifeq ($(DETECTED_OS), Darwin)
    CXXFLAGS += -mmacosx-version-min=15.2
    FRAMEWORKS = -framework Security -framework CoreFoundation
endif

# In the CI, the CARGO_TARGET_DIR is overridden to a custom path. If the env var is set, use it, else use the default target directory.
TARGET_DIR = $(if $(CARGO_TARGET_DIR),$(CARGO_TARGET_DIR),target)

# Libraries
LIBS = $(TARGET_DIR)/debug/libcpp_driver_cxx.a

# Source file
SRC = tds-x/cpp-driver-cxx/src/main.cc

# Include directories. These are generated by Cxxbridge and are required for the C++ code to compile.
INCLUDES = -I$(TARGET_DIR)/cpp-driver-cxx/src -I$(TARGET_DIR)/cxxbridge/ -I$(TARGET_DIR)/cxxbridge/cpp-driver-cxx/src

# Output directory
OUT_DIR = $(TARGET_DIR)/cpp-sample

# Output file
ifeq ($(DETECTED_OS), Windows)
    OUT = $(OUT_DIR)/test.exe
else
    OUT = $(OUT_DIR)/test.out
endif

# Build target
all: cargo_build $(OUT)

# Run cargo build to compile Rust code
cargo_build:
	cargo build --frozen -vv 

# Compile the C++ code
$(OUT): $(SRC) | $(OUT_DIR)
	$(CXX) $(SRC) $(INCLUDES) $(LIBS) $(CXXFLAGS) $(FRAMEWORKS) -o $(OUT)

# Create the output directory if it doesn't exist
$(OUT_DIR):
	mkdir -p $(OUT_DIR)

# Clean target
clean:
	rm -f $(OUT)
