# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: RUST-1ES-POOL-WUS3
  demands:
    - imageOverride -equals RUST-1ES-UBU

steps:
- template: templates/install-ubuntu-dependency.yaml
  parameters:
    installAzCli: true

- template: templates/azure-cli-login-template.yml

- script: |
    cd containers
    ./buildimages-x64.sh
  displayName: 'Build and publish container images.'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Magnitude Test'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'cd containers && ./buildimages-arm64.sh'
#   retryCountOnTaskFailure: 5
