name: Rust and C++ Prototype build for ${{parameters.buildType}} platform
trigger: none

parameters:
- name: buildType
  displayName: Type of the build to produce
  type: string
  values:
  - Both
  - Debug
  - Release
  default: Both

jobs:
- job: Build
  strategy:
    matrix:
      Windows:
        poolName: Hosted Windows 2019 with VS2019
        vmImage:
        cargoTargetDir: C:\cargo_target_dir
        buildTarget: Windows
      Linux:
        poolName: Azure Pipelines
        vmImage: ubuntu-latest
        cargoTargetDir: $(Build.SourcesDirectory)
        buildTarget: Linux
      MacOS:
        poolName: Azure Pipelines
        vmImage: macOS-latest
        cargoTargetDir: $(Build.SourcesDirectory)
        buildTarget: MacOS
  pool:
    name: $(poolName)
    vmImage: $(vmImage)
  variables:
    # For details on this CARGO_TARGET_DIR setting, see https://eng.ms/docs/more/rust/topics/onebranch-workaround
    CARGO_TARGET_DIR: $(cargoTargetDir)
  steps:
  - task: RustInstaller@1
    displayName: Install Rust Toolchain
    inputs:
      toolchainFeed: https://sqlclientdrivers.pkgs.visualstudio.com/SqlDevX/_packaging/RustTools/nuget/v3/index.json

  - task: CargoAuthenticate@0
    displayName: Authenticate with Azure Artifacts
    inputs:
      configFile: '.cargo/config.toml'

  - script: cargo fetch
    displayName: Fetch Crates
    env:
      CARGO_REGISTRIES_ONELAKECLIENT_TOKEN: $(OneLakeClientSecret)

  - script: cargo build --frozen 2>&1
    displayName: Rust Debug Build
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))

  - script: cargo build --frozen --release 2>&1
    displayName: Rust Release Build
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Release'), eq('${{parameters.buildType}}', 'Both')))


  - script: cargo clippy --frozen -- -D warnings
    displayName: Rust Clippy Lint
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Release'), eq('${{parameters.buildType}}', 'Both')))

  - script: cargo install junitify
    displayName: Install JUnitify
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Release'), eq('${{parameters.buildType}}', 'Both')))


  - script: RUSTC_BOOTSTRAP=1 cargo test -- --format=json -Z unstable-options --report-time | junitify --out testresults/
    displayName: Test Debug and create Junit report
    condition: and(succeeded(), ne(variables.buildTarget, 'Windows'), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))

  - script: cargo fmt --check
    displayName: Check Format
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))


  - script: |
      set RUSTC_BOOTSTRAP=1 
      cargo test -- --format=json -Z unstable-options --report-time | junitify --out testresults/
    displayName: Test Debug and create Junit report
    condition: and(succeeded(), eq(variables.buildTarget, 'Windows'), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/testresults/*.xml'

  - task: MSBuild@1
    displayName: C++ Debug Build
    condition: and(succeeded(), eq(variables.buildTarget, 'Windows'), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))
    inputs:
      solution: '**/*.sln'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Debug'

  - task: MSBuild@1
    displayName: C++ Release Build
    condition: and(succeeded(), eq(variables.buildTarget, 'Windows'), or(eq('${{parameters.buildType}}', 'Release'), eq('${{parameters.buildType}}', 'Both')))
    inputs:
      solution: '**/*.sln'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'Release'

  - task: CopyFiles@2
    displayName: Copy Rust Debug Build
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))
    inputs:
      SourceFolder: '$(CARGO_TARGET_DIR)/debug'
      Contents: |
        *
        !.cargo-lock
      TargetFolder: '$(Build.ArtifactStagingDirectory)/debug'

  - task: CopyFiles@2
    displayName: Copy Rust Release Build
    condition: and(succeeded(), or(eq('${{parameters.buildType}}', 'Release'), eq('${{parameters.buildType}}', 'Both')))
    inputs:
      SourceFolder: '$(CARGO_TARGET_DIR)/release'
      Contents: |
        *
        !.cargo-lock
      TargetFolder: '$(Build.ArtifactStagingDirectory)/release'

  - task: CopyFiles@2
    displayName: Copy C++ Debug Build
    condition: and(succeeded(), eq(variables.buildTarget, 'Windows'), or(eq('${{parameters.buildType}}', 'Debug'), eq('${{parameters.buildType}}', 'Both')))
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\prototype\ffi-prototype\x64\Debug'
      Contents: 'ffi-app.*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\Debug'

  - task: CopyFiles@2
    displayName: Copy C++ Release Build
    condition: and(succeeded(), eq(variables.buildTarget, 'Windows'), or(eq('${{parameters.buildType}}', 'Release'), eq('${{parameters.buildType}}', 'Both')))
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\prototype\ffi-prototype\x64\Release'
      Contents: 'ffi-app.*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\Release'

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Drop
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: $(buildTarget)
      publishLocation: Container
