name: Rust and C++ Prototype build for ${{parameters.buildType}} platform
trigger: none

parameters:
- name: buildType
  displayName: Type of the build to produce
  type: string
  values:
  - Both
  - Debug
  - Release
  default: Both

jobs:
- job: Build_Windows
  pool:
    name: RUST-1ES-POOL
    demands:
      - imageOverride -equals RUST-Win22-Sql22
  variables:
    # For details on this CARGO_TARGET_DIR setting, see https://eng.ms/docs/more/rust/topics/onebranch-workaround
    CARGO_TARGET_DIR: C:\cargo_target_dir
  steps:
    - template: templates/sql-setup-template.yml
      parameters:
        buildTarget: Windows
    - template: templates/build-template.yml
      parameters:
        buildTarget: Windows
        buildType: ${{ parameters.buildType }}
- job: Build_Linux
  pool:
    name: RUST-1ES-POOL
    demands:
      - imageOverride -equals RUST-1ES-UBU
  variables:
    # For details on this CARGO_TARGET_DIR setting, see https://eng.ms/docs/more/rust/topics/onebranch-workaround
    CARGO_TARGET_DIR: $(Build.SourcesDirectory)
  steps:
    - template: templates/sql-setup-template.yml
      parameters:
        buildTarget: Linux
    - template: templates/build-template.yml
      parameters:
        buildTarget: Linux
        buildType: ${{ parameters.buildType }}
- job: Build_MacOS
  pool:
    name: Azure Pipelines
    vmImage: macOS-latest
  variables:
    # For details on this CARGO_TARGET_DIR setting, see https://eng.ms/docs/more/rust/topics/onebranch-workaround
    CARGO_TARGET_DIR: $(Build.SourcesDirectory)
  steps:
    - template: templates/sql-setup-template.yml
      parameters:
        buildTarget: MacOS
    - template: templates/build-template.yml
      parameters:
        buildTarget: MacOS
        buildType: ${{ parameters.buildType }}
