;SQL Server 2022 Configuration File
[OPTIONS]

ACTION="Install"
FEATURES=SQL,Tools,REPLICATION
INSTANCENAME=MSSQLSERVER
SQLSYSADMINACCOUNTS="BUILTIN\Administrators"

QUIET="True"
ENU="True"
UpdateEnabled="False"
USEMICROSOFTUPDATE="False"
TCPENABLED="1"

IACCEPTPYTHONLICENSETERMS="True"
IACCEPTROPENLICENSETERMS="True"
SUPPRESSPRIVACYSTATEMENTNOTICE="True"
SUPPRESSPAIDEDITIONNOTICE="True"
