FROM tdslibrs.azurecr.io/alpine:3.18


# Install prerequisites
RUN apk update

RUN apk add --no-cache \
    ca-certificates \
    zstd \
    tar \
    gcc \
    g++ \
    make \
    pkgconfig \
    openssl-dev \
    openssl-libs-static \
    musl-dev \
    curl

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN export PATH="$HOME/.cargo/bin:$PATH" && \
    cargo install cargo-nextest --version 0.9.96 --locked

WORKDIR /workspace

CMD ["sh"]