#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TdsDataType {
    Void = 0x1F,
    Image = 0x22,
    Text = 0x23,
    Guid = 0x24,
    VarBinary = 0x25,
    IntN = 0x26,
    VarChar = 0x27,
    DateN = 0x28,
    TimeN = 0x29,
    DateTime2N = 0x2A,
    DateTimeOffsetN = 0x2B,
    Binary = 0x2D,
    Char = 0x2F,
    Int1 = 0x30,
    Bit = 0x32,
    Int2 = 0x34,
    Decimal = 0x37,
    Int4 = 0x38,
    DateTim4 = 0x3A,
    Flt4 = 0x3B,
    Money = 0x3C,
    DateTime = 0x3D,
    Flt8 = 0x3E,
    Numeric = 0x3F,
    SsVariant = 0x62,
    NText = 0x63,
    BitN = 0x68,
    DecimalN = 0x6A,
    NumericN = 0x6C,
    FltN = 0x6D,
    MoneyN = 0x6E,
    DateTimN = 0x6F,
    Money4 = 0x7A,
    Int8 = 0x7F,
    BigVarBinary = 0xA5,
    BigVarChar = 0xA7,
    BigBinary = 0xAD,
    BigChar = 0xAF,
    NVarChar = 0xE7,
    NChar = 0xEF,
    Udt = 0xF0,
    Xml = 0xF1,
    Json = 0xF4,

    #[default]
    None = 0x00,
}
impl From<u8> for TdsDataType {
    fn from(value: u8) -> Self {
        match TdsDataType::from_u8(value) {
            Some(data_type) => data_type,
            None => TdsDataType::None,
        }
    }
}

impl TdsDataType {
    /// Converts an integer value to the corresponding SqlDataType, if valid.
    pub fn from_u8(value: u8) -> Option<TdsDataType> {
        match value {
            0x1F => Some(TdsDataType::Void),
            0x22 => Some(TdsDataType::Image),
            0x23 => Some(TdsDataType::Text),
            0x24 => Some(TdsDataType::Guid),
            0x25 => Some(TdsDataType::VarBinary),
            0x26 => Some(TdsDataType::IntN),
            0x27 => Some(TdsDataType::VarChar),
            0x28 => Some(TdsDataType::DateN),
            0x29 => Some(TdsDataType::TimeN),
            0x2A => Some(TdsDataType::DateTime2N),
            0x2B => Some(TdsDataType::DateTimeOffsetN),
            0x2D => Some(TdsDataType::Binary),
            0x2F => Some(TdsDataType::Char),
            0x30 => Some(TdsDataType::Int1),
            0x32 => Some(TdsDataType::Bit),
            0x34 => Some(TdsDataType::Int2),
            0x37 => Some(TdsDataType::Decimal),
            0x38 => Some(TdsDataType::Int4),
            0x3A => Some(TdsDataType::DateTim4),
            0x3B => Some(TdsDataType::Flt4),
            0x3C => Some(TdsDataType::Money),
            0x3D => Some(TdsDataType::DateTime),
            0x3E => Some(TdsDataType::Flt8),
            0x3F => Some(TdsDataType::Numeric),
            0x62 => Some(TdsDataType::SsVariant),
            0x63 => Some(TdsDataType::NText),
            0x68 => Some(TdsDataType::BitN),
            0x6A => Some(TdsDataType::DecimalN),
            0x6C => Some(TdsDataType::NumericN),
            0x6D => Some(TdsDataType::FltN),
            0x6E => Some(TdsDataType::MoneyN),
            0x6F => Some(TdsDataType::DateTimN),
            0x7A => Some(TdsDataType::Money4),
            0x7F => Some(TdsDataType::Int8),
            0xA5 => Some(TdsDataType::BigVarBinary),
            0xA7 => Some(TdsDataType::BigVarChar),
            0xAD => Some(TdsDataType::BigBinary),
            0xAF => Some(TdsDataType::BigChar),
            0xE7 => Some(TdsDataType::NVarChar),
            0xEF => Some(TdsDataType::NChar),
            0xF0 => Some(TdsDataType::Udt),
            0xF1 => Some(TdsDataType::Xml),
            0xF4 => Some(TdsDataType::Json),
            _ => None,
        }
    }
}
