/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsClientContext {
  serverName: string
  port: number
  userName: string
  password: string
  database: string
  trustServerCertificate: boolean
}
export declare class Connection { }
