[registries]
RustTools = { index = "sparse+https://sqlclientdrivers.pkgs.visualstudio.com/SqlDevX/_packaging/RustTools/Cargo/index/" }

[registry]
global-credential-providers = ["cargo:token", "cargo:wincred"]

[source.crates-io]
replace-with = "RustTools"

[alias]
bfmt = "fmt -- --check"
bclippy = "clippy --frozen -- -D warnings"
btest = "test -- --format=json -Z unstable-options --report-time"
