[alias]
bfmt = "fmt -- --check"
bclippy = "clippy --frozen --all-features --all-targets -- -D warnings"
btest = "llvm-cov nextest --frozen --no-report --all-targets --no-fail-fast --profile ci --success-output immediate"
